apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-race-engineer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f1-race-engineer
  template:
    metadata:
      labels:
        app: f1-race-engineer
    spec:
      containers:
        - name: f1-race-engineer
          image: akhildoddi/f1-race-engineer:3.0
          ports:
            - containerPort: 8081