apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-api
  template:
    metadata:
      labels:
        app: f1-api
    spec:
      containers:
        - name: f1-api
          image: hashicorp/http-echo:1.0
          args:
            - "-text=Hello from the F1 API!"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: f1-api-service
  namespace: default
spec:
  selector:
    app: f1-api
  ports:
    - port: 5678
      targetPort: 5678